### ISSUE TITLE
Your OpenAI plugin

### ISSUE THREAD

**Issue by olimorris** [stevearc/dotfiles#2]
Hey Steve!

Firstly, Happy Holidays.

Secondly, I came across your OpenAI plugin, [here](https://github.com/stevearc/dotfiles/tree/master/vimplugins/openai.nvim). Mind if I riff on it? I don't intend to do anything in terms of sharing (don't want to open myself up for the maintenance and hassle of it all) but would love to tweak it for my own workflow.

**Comment by stevearc** [comment]
Yeah go for it! I made it to mess around, but there are so many other AI LLM plugins that it didn't seem like there would be much point to polishing it up to the point of publishing. Feel free to take anything you want from there.
